export const SWITCH_GAME_MODE = 'SWITCH_GAME_MODE';
export const SWITCH_PLAYER_MODE = 'SWITCH_PLAYER_MODE';
export const PLAY_GAME = 'PLAY_GAME';
export const RESET_GAME = 'RESET_GAME';
export const SIMULATE_GAME = 'SIMULATE_GAME';
export const INITIALIZE_STATE = 'INITIALIZE_STATE';